// src/constants/notificationTypes.js
const NOTIFICATION_TYPES = {
  PAYMENT_REMINDER: 'PAYMENT_REMINDER',
  OVERDUE_ALERT: 'OVERDUE_ALERT',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  CREDIT_LIMIT_WARNING: 'CREDIT_LIMIT_WARNING',
  SYSTEM: 'SYSTEM',
};

module.exports = NOTIFICATION_TYPES;
